development:
  pool: 5
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: how2_development

test:
  pool: 5
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: how2_test
