# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0c2972ab131146d2b03a329d47ca8a2f55998ec510866286d7d5caac897dab586faad061190d0c69b2907e78f2bfabc1e58ab550f459667ac062202b8e7ce4e

test:
  secret_key_base: 6bce7ea9cf92d4234110c243fa276cf1eddc336166651d426eed1d731e1e1a5914d1f7fbd7ecb9049d0b4de2bae80c27546798312dc4b6a7d355385822c40682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
